name: frictionless

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  frictionless-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate data
        uses: frictionlessdata/repository@v2
