name: data packages validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frictionless-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Test Action
        uses: shashigharti/vizai-app@v2
